services:
  - type: web
    name: garena-fe
    env: dotnet
    plan: free
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/GarenaFrontEnd.dll"
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
